### PR TITLE
Pretty Discord embeds 😍 

### PR DESCRIPTION
**Pull request by clemmyn23**
## Changes:
* Discord embed 🎉 . Messages now have pretty colour (rarity), proper formatting and thumbnails. 
* Restructured repo. No more clone-copy-pasting to install the cog. 
* Calling search with slot num: `[p]bopae setname slotnum` won't send the set bonuses notes. 
* Instead, calling search without slot num: `[p]bopae setname` will send only the set bonuses notes.
* Disabled `compare` until I find a prettier way to format the info
* Minor cleanups and small stuff 
* ⚠️  No tests written yet. That should happen soon. In the meantime file issues or ping me for bugs.

## Notes:
* Refer to data/ebondrake.json for the new 'rarity' and 'imageUrl' fields in json.

## Install:
1. Pick one:  
ssh `[p]cog repo add Cobalt-Blindfold git@github.com:clemmyn23/Cobalt-Blindfold.git`  
https `[p]cog repo add Cobalt-Blindfold https://github.com/clemmyn23/Cobalt-Blindfold.git`
2. `[p]cog install bopae`

image

### CODE REVIEW

**Comment by clemmyn23** [comment]
* Added chokma, mugan data
* added exact matching check for tags. E.g. `!bopae bt` returns black tower (chokma) instead of none (failing the len >= 3 check)
* bug fix for displaying json files without bonus 5 and 8 fields 
* other minor bug fixes

**Comment by hackthecode** [comment]
Аgain a great job! Thank you for your hard work !

**Comment by clemmyn23** [comment]
@hackthecode thanks for your work as well. Hope you don't mind me taking your commits :)

**Comment by hackthecode** [comment]
of coure i do not mind :)
btw in chokma.json missing set bonus info for WL
3 set - "WL": "[RB] bombardment damage increase by 15%."
8 set - "WL": "[TAB] obliterate cooldown decrease by 30%"
Regards!
pfjb9wo

**Comment by clemmyn23** [comment]
Oh I left out the ranged classes cuz I got lazy 😝 
Will add those in and update the other sets soon

**Pull request merged**
